# Include header for JavaScript Indexer. Do not delete!
# Modify if you wish.

# A commented line is like this one. This line will be ignored.

#Standard header.
<HTML>
<HEAD>
<TITLE>Pretraga</TITLE>

#IMPORTANT:
#-----------
#If you use a non english alphabet then modify this meta tag according to your charset.
#<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">

#You can use a external style file.
<LINK REL='stylesheet' TYPE='text/css' HREF='Styles.css'>

##Also you can use this style (default).
#<style>
#<!--
##Body color & font.
#body{font-family:arial,sans-serif; font-size:14px; background-color: 'white'}

##Any table colors.
#table{font-family:arial,sans-serif;font-size:14px; background-color: 'white'}

##Results table colors.
#.t{font-family:arial,sans-serif; font-size:13px; background-color: 'white'}

##Link color and font
#a:link{color:#00c}
#a:visited{color:#551a8b}
#a:active{color:#f00}

##"Go back", "Go to Top", URL links
#.h{font-size:16px}

##Results links
#.l{font-size:16px}

#//-->
#</style>

#The frame which will display the page
#<base target="main">

#<script language="JavaScript" type="text/javascript" SRC="search.js"></script>

</HEAD>

#Classic colors. Works with older browsers.
# <body link='#00c' vlink='#551a8b' alink='#f00' background='' bgColor='#FFFFFF' bgProperties='fixed'>

<BODY background="BackGround.gif">

#This displays the input box in the results page. Use it on single frame pages (don't work with all browsers).
#<div align='center'>
#<form name="JF1" action="javascript:FND(document.JF1.JT1.value)">
#<input type="text" name="JT1" size="10">
#<input type="submit" value="Search">
#</form>
#</div>
#<BR>


#Set the font of the page in classic way. Works with older browsers.
# <font size='2' color = 'black'><U>

#You can add here any text and images to show before the results.
#Do not use javascripts which write on the document.

